config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users

  resources :survey_questions do
    resources :user_responses
  end

  resources :password_resets

  resources :user_responses

  resources :itineraries

  resources :surveys

  resources :sessions, only: [:new, :create, :destroy]

  resources :preferences, only: [:new, :create, :destroy]

  resources :terms_of_use, only: [:index]

  root "itineraries#new"

  get 'logout', to: "sessions#destroy", as: 'logout'

  get '/itineraries/:id/delete', to: "itineraries#destroy", as: 'delete'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password

	validates :first_name, :last_name, :email, :agreed, presence: true
  validates_uniqueness_of :email

  has_many :preferences
  has_many :itineraries
  has_many :activities, through: :itineraries
  has_many :user_responses
  has_many :survey_responses, through: :user_responses


  def necessary_preferences
  	self.preferences.select { |preference| preference.is_necessary? == true }
  end

  def supplemental_preferences
  	self.preferences.select { |preference| preference.is_necessary? == false }
  end

  def submitted_preferences
  	supplemental_preferences = self.supplemental_preferences
  	submitted_preferences = supplemental_preferences.sample(rand(supplemental_preferences.length))
  	submitted_preferences = submitted_preferences + self.necessary_preferences
  	return submitted_preferences
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.forgot_password(self).deliver# This sends an e-mail with a link for the user to reset the password
  end
  # This generates a random password reset token for the user
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(secure_params)
    @survey = SurveyQuestion.find_by(order: 1)
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_survey_path
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  def show
    if logged_in?
      if current_user.id == params[:id].to_i
       @itineraries = current_user.itineraries.where(confirmed?: true)
       return  "users/show"
     else
      redirect_to new_itinerary_path
     end
    else
      redirect_to new_session_path
    end
  end

  def index
  end

  private

  def secure_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :agreed)
  end

end

app/views/users/_list.html.erb
<li class="itinerary-list-activity"><span class="itinerary-li-partial list-itinerary-name"><%= itinerary.name %></span><br /><span class="itinerary-li-partial" ><%= itinerary.date %></span><br /><span class="itinerary-li-partial" ><%= itinerary.location %></span><br /><span class="itinerary-li-partial itinerary-list-link"><%= link_to "show me", itinerary %> | <a href="/itineraries/<%= itinerary.id %>/delete" > forget it... delete</a></span></li>

app/views/users/new.html.erb
  <div class="w3-container w3-black">
      <h2><i class="fa w3-margin-center"></i>Get Started</h2>
      <p>Sign up, and we'll share awesome things.</p>
    </div>
    <div class="w3-container w3-white w3-padding-16">
      <h3>Step 1: register</h3><p>
<!-- <h4 class = "form-signin-heading">Step 1: Sign Up</h4> -->

<% if @errors %>
<ul>
  <% @errors.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user, :html => {class: "form-signin"} do |form| %>
  <p>
    <%= form.text_field :first_name, placeholder: "first name", class: "form-control"%>
  </p>
  <p>
    <%= form.text_field :last_name, placeholder: "last name", class: "form-control" %>
  </p>
  <p>
    <%= form.text_field :email, placeholder: "email", class: "form-control" %>
  </p>
  <p>
    <%= form.password_field :password, placeholder: "password", class: "form-control" %>
  </p>
    <div class="checkbox">
      <div class="terms-agree">
        <%= form.check_box :agreed, {}, 'true', nil %>
      </div>
      <div class="terms-agree">
        <label for="terms-agree-button">I Agree To <%= link_to "Terms of Use", terms_of_use_index_path %></a>.</label>
      </div>
    </div>
  <p>
    <%= form.submit "Sign up!", class: "w3-button w3-black" %>
  </p>
<% end %>
</div>

app/views/users/show.html.erb
<header class="w3-display-container w3-content " style="max-width:1500px">
    <div class="w3-container w3-black">
      <h2><i class="fa w3-margin-right"></i><%= current_user.first_name %>'s PlanDuhs:</h2>
    </div>
</header>

<ul class="itineraries-list-profile">
<% @itineraries.each do |itinerary| %>
	<%= render partial: 'list', locals: {itinerary: itinerary} %>
<% end %>
</ul>