config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users

  resources :survey_questions do
    resources :user_responses
  end

  resources :password_resets

  resources :user_responses

  resources :itineraries

  resources :surveys

  resources :sessions, only: [:new, :create, :destroy]

  resources :preferences, only: [:new, :create, :destroy]

  resources :terms_of_use, only: [:index]

  root "itineraries#new"

  get 'logout', to: "sessions#destroy", as: 'logout'

  get '/itineraries/:id/delete', to: "itineraries#destroy", as: 'delete'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    @questions = SurveyQuestion.page(params[:page]).per(1)
    @answers = SurveyResponse.all
  end

  def show
    id = params[:id].to_i % 7
    if id == 0
      id = 7
    end
  	@question = SurveyQuestion.find_by(order: id)
    @page = @question.order
    render 'show'
  end

  def new
    survey = SurveyQuestion.find_by(order: 1)
    redirect_to survey_path(survey)
  end

end

app/views/surveys/_multiple_choice_question.html.erb
<div class>
  <strong><%= question.question_text %></strong>
</div>

app/views/surveys/_multiple_choice_response.html.erb
<% if page < 7 %>
  <div class="pag-links">
    <form  class="w3-container w3-card-4 survey-form" action="/survey_questions/<%= question.id %>/user_responses" method="POST">
        <select class="w3-select" name="answer">
          <% question.responses.each do |response| %>
            <option value="<%= response.response %>"  ><%= response.response %></option>
          <% end %>
        </select>
        <%= hidden_field_tag 'page', '1', {class: 'js-form-page'}%>
        <button class="w3-btn w3-black multi-button" type="submit"><i class="fa "></i> NEXT</button>
      </form>
  </div>
<% else %>
  <div class="pag-links">
    <form  class="w3-container w3-card-4 survey-form" action="/preferences" method="POST">
        <select class="w3-select" name="answer">
          <% question.responses.each do |response| %>
            <option value="<%= response.response %>"  ><%= response.response %></option>
          <% end %>
        </select>
        <%= hidden_field_tag 'page', '1', {class: 'js-form-page'}%>
        <button class="w3-btn w3-black multi-button" type="submit"><i class="fa "></i> NEXT</button>
      </form>
  </div>
<% end %>

<% if question.id == 5 %>
<img src="https://media.timeout.com/images/103817003/image.jpg" alt="physical" style="width:100%" class="survey-image">
<% elsif question.id == 6 %>
<img src="http://townwall.ca/images/gallery/blog/77951493926345_H49A7049.jpg" style="width:100%" class="survey-image">
<% else %>
<img src="https://thumbs.dreamstime.com/b/people-enjoying-outdoors-activities-city-park-recreation-s-samara-russia-may-sunny-day-67052918.jpg" style="width:100%" class="survey-image">
<% end %>

app/views/surveys/_open_ended_question.html.erb
<div class>
  <strong><%= question.question_text %></strong>
</div>

app/views/surveys/_open_ended_response.html.erb
<div>
  <form class="js--form" action="/survey_questions/<%= question.id %>/user_responses" method="POST">
      <textarea class="form-control" rows="4" id="comment" name="answer" placeholder="Enter all restrictions here:"></textarea>


        <button class="w3-btn w3-black open-question-button" type="submit"><i class="fa "></i> NEXT</button>
     <!--  <input type="submit" value="NEXT"> -->
    </form>
</div>

<img src="https://www.weddingbee.com/wp-content/uploads/2017/03/food-allergy-214771.jpg" alt="physical" style="width:100%" class="survey-image">

app/views/surveys/_yes_no_question.html.erb
<div class>
  <strong><%= question.question_text %></strong>
</div>

app/views/surveys/_yes_no_response.html.erb
<div class="pag-links">
  <form class="js--form w3-container w3-card-4" action="/survey_questions/<%= question.id %>/user_responses" method="POST">
      <select class="w3-select" name="answer">
        <% question.responses.each do |response| %>
        <option value="<%= response.response %>"  ><%= response.response %></option>
        <% end %>
      </select>
       <button class="w3-btn w3-black multi-button" type="submit"><i class="fa "></i> NEXT</button>
      <!-- <input type="submit" value="submit"> -->
    </form>
</div>

<% if question.id == 3 %>
<img src="http://americansocialbar.com/wp-content/uploads/2016/01/group.jpg" alt="physical" style="width:100%" class="survey-image">
<% else %>
<img src="https://virtuagym.com/blog/wp-content/uploads/2016/11/client-motivation-coach-partnership.jpg" alt="physical" style="width:100%" class="survey-image">
<% end %>

app/views/surveys/index.html.erb
<div class="w3-container w3-black">
      <h2><i class="fa w3-margin-center"></i>Get Started</h2><p>Getting started with PlanDuh is easy
    </div>
    <div class="w3-container w3-white w3-padding-16">
      <!-- <h3><strong>Step 2: Set Preferences</strong></h3> -->

<%= render partial: "shared/errors", locals: {errors: @errors} if @errors %>

  <div id="js--questions">

    <% @questions.each do |question| %>
      <% if question.version == "Yes/No" %>
        <div class="w3-container w3-center">
            <hr>
          </div>

            <div class="w3-row-padding">
              <div class="w3-content">
                <div class="w3-card">
                  <img src="https://images.pexels.com/photos/7753/sun-ball-tennis-court.jpg?w=1260&h=750&auto=compress&cs=tinysrgb" alt="physical" style="width:100%" class="survey-image">
                <div class="w3-container survey-form">
                  <%= render partial: "yes_no_question", locals: {question: question} %>
                  <%= render partial: 'yes_no_response', locals: {question: question} %>
                </div>
              </div>
            </div>
        </div>


      <% elsif question.version == "Multiple Choice" %>
          <div class="w3-container w3-center">
            <hr>
          </div>

            <div class="w3-row-padding">
              <div class="w3-content">
                <div class="w3-card">
                  <img src="https://images.pexels.com/photos/7753/sun-ball-tennis-court.jpg?w=1260&h=750&auto=compress&cs=tinysrgb" alt="physical" style="width:100%" class="survey-image">
                <div class="w3-container survey-form">
                 <%= render partial: "multiple_choice_question", locals: {question: question} %>
                <%= render partial: 'multiple_choice_response', locals: {question: question} %>
                </div>
              </div>
            </div>
        </div>
      <!-- </hr> -->
      <% elsif question.version == "Open-ended" %>
       <div class="w3-container w3-center">
            <hr>
          </div>

            <div class="w3-row-padding">
              <div class="w3-content">
                <div class="w3-card">
                  <img src="https://www.weddingbee.com/wp-content/uploads/2017/03/food-allergy-214771.jpg" alt="physical" style="width:100%" class="survey-image">
                <div class="w3-container survey-form">
                 <p> <%= render partial: "open_ended_question", locals: {question: question} %></p>
                 <p> <%= render partial: "open_ended_response", locals: {question: question} %></p>
                </div>
              </div>
            </div>
        </div>
     <% end  %>
    <% end %>
  </div>

</div>


  <div id="js--save-pref-button">
      <% if logged_in? && current_user.user_responses.count == 7  %>
        <!-- how to remove step2: set preferences and render new text -->
       <center> <%= button_to "Now Go Planduh!", preferences_path, method: 'POST', class: "w3-btn w3-green btn btn-lg btn-success" %> </center>
      <% end %>
  </div>

app/views/surveys/show.html.erb
<div class="w3-container w3-black">
  <h2><i class="fa w3-margin-center"></i>Get Started</h2>
  <p>By answering these seven questions (ONLY ONCE!), you'll help us make your PlanDuh amazing.</p>
</div>
<div class="w3-container w3-white w3-padding-16">

<%= render partial: "shared/errors", locals: {errors: @errors} if @errors %>


  <div id="js--questions">

      <% if @question.version == "Yes/No" %>
        <div class="w3-container w3-center">
            <hr>
          </div>

            <div class="w3-row-padding">
              <div class="w3-content">
                <div class="w3-card">
                  <div class="w3-container survey-form">
                    <%= render partial: "yes_no_question", locals: {question: @question} %>
                    <%= render partial: 'yes_no_response', locals: {question: @question} %>
                  </div>
              </div>
            </div>
        </div>

      <% elsif @question.version == "Multiple Choice" %>
          <div class="w3-container w3-center">
            <hr>
          </div>

            <div class="w3-row-padding">
              <div class="w3-content">
                <div class="w3-card">
                  <div class="w3-container survey-form">
                    <%= render partial: "multiple_choice_question", locals: {question: @question} %>
                    <%= render partial: 'multiple_choice_response', locals: {question: @question, page: @page} %>
                  </div>
              </div>
            </div>
        </div>

      <% elsif @question.version == "Open-ended" %>
       <div class="w3-container w3-center">
            <hr>
          </div>

            <div class="w3-row-padding">
              <div class="w3-content">
                <div class="w3-card">
                  <div class="w3-container survey-form">
                     <p> <%= render partial: "open_ended_question", locals: {question: @question} %></p>
                     <p> <%= render partial: "open_ended_response", locals: {question: @question} %></p>
                  </div>
              </div>
            </div>
        </div>
     <% end  %>


  </div>
</div>