config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users

  resources :survey_questions do
    resources :user_responses
  end

  resources :password_resets

  resources :user_responses

  resources :itineraries

  resources :surveys

  resources :sessions, only: [:new, :create, :destroy]

  resources :preferences, only: [:new, :create, :destroy]

  resources :terms_of_use, only: [:index]

  root "itineraries#new"

  get 'logout', to: "sessions#destroy", as: 'logout'

  get '/itineraries/:id/delete', to: "itineraries#destroy", as: 'delete'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/views/layouts/application-good.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>PlanDuh</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
   <section class="body-container">
    <nav id="js-main-header class="main-header main-header--static">
      <ul>
      <% if logged_in? %>
          <li>Welcome, <%= link_to "#{current_user.first_name}",  @current_user %></li>
         | <li><%= link_to "Logout", logout_path %></li>
         | <li><%= link_to "Home", root_path %></li>
      <% else %>
         | <li><%= link_to "Register", new_user_path %></li>
         | <li><%= link_to "Login", new_session_path %></li>
         | <li><%= link_to "Home", root_path %></li>
      <% end %>
      </ul>
    </nav>

    <div class="layout-header">Title</div>
    <%= yield %>
  </section>
  </body>
</html>

app/views/layouts/application-original.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRegistrationSkeleton</title>
    <%= csrf_meta_tags %>
    <!-- Begin requirement for bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!-- End requirement for bootstrap -->

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <section class="body-container">
    <nav id="js-main-header class="main-header main-header--static">
      <ul>
      <% if logged_in? %>
          <li>Welcome, <%= link_to "#{current_user.first_name}",  @current_user %></li>
         | <li><%= link_to "Logout", logout_path %></li>
         | <li><%= link_to "Home", root_path %></li>
      <% else %>
         | <li><%= link_to "Register", new_user_path %></li>
         | <li><%= link_to "Login", new_session_path %></li>
         | <li><%= link_to "Home", root_path %></li>
      <% end %>
      </ul>
    </nav>

    <div class="layout-header">Title</div>
    <%= yield %>
  </section>


  <!-- Begin requirement for bootstrap -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
<!-- end requirement for bootstrap -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PlanDuh</title>

    <%= csrf_meta_tags %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application',  media: 'all' %>
    <%= javascript_include_tag  'application' %>
    <!-- Test Styling -->
    <link rel="icon" href="https://i.imgur.com/cq2VXPS.png">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
    </style>

  </head>

  <body cz-shortcut-listen="true" >

    <div class="container">

    <nav class="navbar navbar-expand-md navbar-dark w3-black">
    <% if logged_in? && current_user.user_responses.count < 6  %>
        <%= link_to "Finish Survey", survey_path(current_response_count), class: "navbar-brand"  %>
    <% else %>
        <%= link_to "Planduh", root_path, class: "navbar-brand"  %>
    <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExample04" style="">
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <li class="nav-item active"><%= link_to "#{current_user.first_name}'s PlanDuhs", user_path(current_user.id), class: "nav-link"  %></li>
            <% if current_user.user_responses.count >= 6 %>
              <li class="nav-item active"><%= link_to "create new", new_itinerary_path, class: "nav-link" %></li>
            <%end%>
            <li class="nav-item active"><%= link_to "logout", logout_path, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item active"><%= link_to "register", new_user_path, class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to "login", new_session_path, class: "nav-link" %></li>
          <% end %>
        </ul>

      </div>
    </nav>

    <main role="main">

      <div class="jumbotron">
        <center>
          <p>
          <img src='https://i.imgur.com/W29FmAv.png' width="150px" />
          </p>
          <br/>
          <% if logged_in? %>
            <p>"Oh, I don't know what to do." <br/>- <span><%= current_user.first_name %></span> before PlanDuh</p>
            <p>"I had a lot of fun." <br />- <span><%= current_user.first_name %></span> after PlanDuh</p>
          <% else %>
            <p>"Oh, I don't know what to do." <br/>- person before PlanDuh</p>
            <p>"I had a lot of fun." <br />- person after PlanDuh</p>
          <% end %>
      </div>


      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end  %>
    <%= yield %>
    </main>

<!-- Footer -->
<footer class="main-footer w3-padding-32 w3-black w3-center">
  <h5 class="footer-question" >What is PlanDuh?</h5>

  <p class="footer-powered-by">Powered by:<br> Adam, Zach, Mitch, Kalier & Nicole <br>PlanDuh Bear, Inc. © 2017</p>
</footer>

</div> <!-- /container -->


</body>


</html>

app/views/layouts/itinerary.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PlanDuh</title>

    <%= csrf_meta_tags %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application',  media: 'all' %>
    <%= javascript_include_tag  'application' %>
    <!-- Test Styling -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
    </style>

  </head>

  <body cz-shortcut-listen="true" >

    <div class="container">

    <nav class="navbar navbar-expand-md navbar-dark w3-black">
      <%= link_to "PlanDuh", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExample04" style="">
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <li class="nav-item active"><%= link_to "#{current_user.first_name}'s PlanDuhs", user_path(current_user.id), class: "nav-link"  %></li>
            <li class="nav-item active"><%= link_to "Logout", logout_path, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item active"><%= link_to "Register", new_user_path, class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to "Login", new_session_path, class: "nav-link" %></li>
          <% end %>
        </ul>

      </div>
    </nav>

    <main role="main">

      <div class="customjumbotron">
        <center>
          <img src='https://i.imgur.com/W29FmAv.png' class="panda" />
        </center>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <% end  %>
    <%= yield %>
    </main>

<!-- Footer -->
<footer class="main-footer w3-padding-32 w3-black w3-center">
  <h5 class="footer-question" >What is PlanDuh?</h5>

  <p class="footer-powered-by">Powered by:<br> Adam, Zach, Mitch, Kalier & Nicole <br>PlanDuh Bear, Inc. © 2017</p>
</footer>

</div> <!-- /container -->


</body>


</html>